import express from "express";
import authController from "../controllers/auth.controller";
import verifyUser from "../middlewares/authmiddleware";
const router = express.Router();
router.post("/register", authController.register);
router.post("/login", authController.login);
router.get("/status", verifyUser, authController.checkUserLoginStatus);
router.post("/refresh", authController.refresh);
router.post("/logout", verifyUser, authController.logout);
export default router;
